// DO NOT EDIT: Code generated by matcha from about.matcha

import gleam/string_builder.{type StringBuilder}

pub fn render_builder() -> StringBuilder {
  let builder = string_builder.from_string("")
  let builder =
    string_builder.append(
      builder,
      "<section class=\"bg-white dark:bg-gray-900\">
    <div class=\"grid max-w-screen-xl px-4 py-8 mx-auto lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12\">
        <div class=\"mr-auto place-self-center lg:col-span-7\">
            <p class=\"max-w-2xl mb-6 font-light text-gray-500 lg:mb-8 md:text-lg lg:text-xl dark:text-gray-400\">A random song of the day generated by pulling a name out of a \"hat\".</p>
            <p class=\"max-w-2xl mb-6 font-light text-gray-500 lg:mb-8 md:text-lg lg:text-xl dark:text-gray-400\">An application that is used to learn Gleam.  Based off of the https://github.com/gleam-wisp/wisp project.  The premise of this site is to also showcase a gift given to me by my son for Christmas, in which he prepared be a container full tiny pieces of paper.  Each piece of paper has a They Might Be Giants song written on it.  Every day, I pull a new song out of the container and queue it up to listen.  One a day for all 366 days of 2024.  To quote Cousin Eddie from Christmas Vacation: \"Clark, That's The Gift That Keeps On Giving The Whole Year.\"</p>

        </div>
        <div class=\"hidden lg:mt-0 lg:col-span-5 lg:flex\">
            <img src=\"/static/tmbgodtlogo.png\" alt=\"They Might Be Giants Song of the Day\">
        </div>
    </div>
</section>
",
    )

  builder
}

pub fn render() -> String {
  string_builder.to_string(render_builder())
}
