name: Build TMBG Song Of The Day
on:
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
          submodules: true

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "24"
          gleam-version: "1.2.0"
          rebar3-version: "3.22.1"

      - uses: actions/setup-node@v3
        with:
          node-version: "^v20.11.0"

      - uses: moonrepo/setup-rust@v1

      - uses: extractions/setup-just@v2

      - run: just build
